#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e

if [ -z "$SKIP_TYPECHECKING" ]; then
    npx tsc
fi

if [ -z "$SKIP_TESTS" ]; then
    npm t
fi

if [ -z "$SKIP_LINTING" ]; then
    npx pretty-quick --staged
fi

